pipeline{
    agent any

    stages{
        stage('Pull code') {
            steps {
                checkout scm
            }
        }
        stage('Download dependency') {
            steps {
                dir("final"){
                    dir("front"){
                        sh 'npm install -g http-server'   
                    }   
                }
            }
        }
        stage('Build') {
            steps {
                dir("final"){
                    dir("front"){
                        sh 'npm run build'   
                    }   
                }
            }
        }
    }
}